name: Publish package

on: 
  push:
    tags:
      - "*"

jobs:
  Publish_to_pipy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env
        run: pip3 install "poetry==1.3.1"
      
      - name: Config poetry 
        run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
      
      - name: Publish
        run: poetry publish --build 
        uses: actions/checkout@v3
  
